// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX2Fi-HIOoly6AKFXI1kcsmCUCCls1AN4',
    appId: '1:1067661594295:web:04b2da67cd248c886f4732',
    messagingSenderId: '1067661594295',
    projectId: 'auth-3a5e1',
    authDomain: 'auth-3a5e1.firebaseapp.com',
    storageBucket: 'auth-3a5e1.appspot.com',
    measurementId: 'G-B0KP9SPRNX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApM6II0N4rWWSgmCZOzqs0jTvM_ApliTs',
    appId: '1:1067661594295:android:803e04fe02e9c5d36f4732',
    messagingSenderId: '1067661594295',
    projectId: 'auth-3a5e1',
    storageBucket: 'auth-3a5e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkg0niG5hgzWJ_8DmZTI9V2Y4U0IJWkx8',
    appId: '1:1067661594295:ios:28f5be6e1731c3fb6f4732',
    messagingSenderId: '1067661594295',
    projectId: 'auth-3a5e1',
    storageBucket: 'auth-3a5e1.appspot.com',
    iosBundleId: 'com.example.authFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkg0niG5hgzWJ_8DmZTI9V2Y4U0IJWkx8',
    appId: '1:1067661594295:ios:602f57215feab8996f4732',
    messagingSenderId: '1067661594295',
    projectId: 'auth-3a5e1',
    storageBucket: 'auth-3a5e1.appspot.com',
    iosBundleId: 'com.example.authFirebase.RunnerTests',
  );
}
